### ISSUE TITLE
cannot get /

### ISSUE THREAD

**Issue by denz8028** [rasjonell/telegram-to-rss#1]
![изображение](https://github.com/rasjonell/telegram-to-rss/assets/125301239/7766798b-d777-41d7-9c84-989384dc4b5b)
cannot use that script

**Comment by rasjonell** [comment]
This is expected as `/` is not a registered route.
The server only serves static files that are in the `public` directory.
If you want to get the RSS feed navigate to `<SERVER_URL>/rss.xml`
